Mysite/students/urls.py
from django.conf.urls import url



from . import views

urlpatterns = [

    url(r'^$', views.index, name='index'),
    url(r'^student_list/$', views.student_list, name='student_list'),
    url(r'^group_list/$', views.group_list, name='group_list'),
    url(r'^exam_list/$', views.exam_list, name='exam_list'),

    url(r'^add_student/$', views.add_student, name='add_student'),
    url(r'^edit_student/(?P<student_id>\d+)/$', views.edit_student, name='edit_student'),
    url(r'^delete_student/(?P<student_id>\d+)/$', views.delete_student, name='delete_student'),

    url(r'^add_group/$', views.add_group, name='add_group'),
    url(r'^edit_group/(?P<group_id>\d+)/$', views.edit_group, name='edit_group'),

    url(r'^add_exam/$', views.add_exam, name='add_exam'),
    url(r'^edit_exam/(?P<exam_id>\d+)/$', views.edit_exam, name='edit_exam'),
    url(r'^delete_exam/(?P<exam_id>\d+)/$', views.delete_exam, name='delete_exam'),

    url(r'^contact_admin/$', views.contact_admin, name='contact_admin'),

    url(r'^journal/$', views.journal, name='journal'),




]

Mysite/students_db/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('students.urls', namespace='students')),
    url(r'^users/', include('users.urls', namespace='users')),
]

Mysite/users/urls.py
from django.conf.urls import url
from django.contrib.auth.views import login


from . import views


urlpatterns = [

	# Сторінка входу

	url(r'^login/$', login, {'template_name':'users/login.html'}, name='login'),
    url(r'^logout/$', views.logout_views, name='logout'),
    url(r'^register/$', views.register, name='register'),



]

Mysite/students/models.py
# -*- coding: utf-8 -*-

from django.db import models
from django.utils.translation import ugettext_lazy as _


# Create your models here.
class Student(models.Model):
    class Meta(object):
        verbose_name = _(u"Student")
        verbose_name_plural = _(u"Students")

    first_name = models.CharField(max_length=256,
                                  blank=False,
                                  verbose_name=_(u"First Name"))

    last_name = models.CharField(max_length=256,
                                 blank=False,
                                 verbose_name=_(u"Last Name"))

    middle_name = models.CharField(max_length=256,
                                   blank=True,
                                   verbose_name=(u"Surname"),
                                   default='')

    student_group = models.ForeignKey('Group',
                                      verbose_name=_(u"Group"),
                                      blank=False,
                                      null=True,
                                      on_delete=models.PROTECT)

    birthday = models.DateField(blank=False,
                                verbose_name=_(u"Birthday"),
                                null=True)

    photo = models.ImageField(blank=True,
                              verbose_name=_(u"Photo"),
                              null=True)

    ticket = models.CharField(max_length=256,
                              blank=False,
                              verbose_name=_(u"Ticket"))

    notes = models.TextField(blank=True,
                             verbose_name=_(u"Additional notes"))

    def __str__(self):
        return self.first_name + " " + self.last_name


class Group(models.Model):

    class Meta(object):
        verbose_name = _(u"Group")
        verbose_name_plural = _(u"Groups")

    title = models.CharField(max_length=256,
                             blank=False,
                             verbose_name=_(u"Name"))

    leader = models.OneToOneField('Student',
                                  verbose_name=_(u"Leader"),
                                  blank=True,
                                  null=True,
                                  on_delete=models.SET_NULL)

    notes = models.TextField(blank=True,
                             verbose_name=_(u"Additional notes"))

    def __str__(self):
        if self.leader:
            return self.title + ' ' + self.leader.first_name + ' ' + self.leader.last_name
        else:
            return self.title


class Exam(models.Model):

    class Meta(object):
        verbose_name = _(u"Exam")
        verbose_name_plural = _(u"Exams")

    title = models.CharField(max_length=256,
                             blank=False,
                             verbose_name=_(u"Subject"))

    data = models.DateTimeField( blank=True,
                                verbose_name=_(u"Data"),
                                null=True)

    ticher_name = models.CharField(max_length=256,
                                   blank=False,
                                   verbose_name=_(u"Teacher"))

    exam_group = models.ForeignKey('Group',
                                        verbose_name=_(u"Group"),
                                        blank=False)

    def __str__(self):
        return self.title


class Journal(models.Model):

    class Meta(object):
        verbose_name = _(u"Monthly Magazine")
        verbose_name_plural = _(u"Monthlys Magazine")

    student = models.ForeignKey('Student',
                                verbose_name=_(u'Student'),
                                blank=False,
                                unique_for_month='date'
                                )

    data = models.DateField(blank=False,
                            verbose_name=_(u"Data"),
                            )

    present_day1 = models.BooleanField(default=False)
    present_day2 = models.BooleanField(default=False)
    present_day3 = models.BooleanField(default=False)
    present_day4 = models.BooleanField(default=False)
    present_day5 = models.BooleanField(default=False)
    present_day6 = models.BooleanField(default=False)
    present_day7 = models.BooleanField(default=False)
    present_day8 = models.BooleanField(default=False)
    present_day9 = models.BooleanField(default=False)
    present_day10 = models.BooleanField(default=False)
    present_day11 = models.BooleanField(default=False)
    present_day12 = models.BooleanField(default=False)
    present_day13 = models.BooleanField(default=False)
    present_day14 = models.BooleanField(default=False)
    present_day15 = models.BooleanField(default=False)
    present_day16 = models.BooleanField(default=False)
    present_day17 = models.BooleanField(default=False)
    present_day18 = models.BooleanField(default=False)
    present_day19 = models.BooleanField(default=False)
    present_day20 = models.BooleanField(default=False)
    present_day21 = models.BooleanField(default=False)
    present_day22 = models.BooleanField(default=False)
    present_day23 = models.BooleanField(default=False)
    present_day24 = models.BooleanField(default=False)
    present_day25 = models.BooleanField(default=False)
    present_day26 = models.BooleanField(default=False)
    present_day27 = models.BooleanField(default=False)
    present_day28 = models.BooleanField(default=False)
    present_day29 = models.BooleanField(default=False)
    present_day30 = models.BooleanField(default=False)
    present_day31 = models.BooleanField(default=False)

    def __str__(self):
        return self.student.last_name

Mysite/students/forms.py
from django import forms
from django.core.urlresolvers import reverse

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit

from .models import Student, Group, Exam

class StudentForm(forms.ModelForm):
    class Meta:
        model = Student
        fields = ('first_name', 'last_name', 'middle_name', 'student_group', 'birthday', 'photo', 'ticket', 'notes')
        help_texts = {'birthday':'* 1995-04-25', }

class GroupsForm(forms.ModelForm):
    class Meta:
        model = Group
        fields = ('title', 'leader')



class ExamForm(forms.ModelForm):
    class Meta:
        model = Exam
        fields = ('title', 'data', 'ticher_name', 'exam_group')
        help_texts = {'data':'2017-10-02 07:25:27',}


class ContactForm(forms.Form):

    def __init__(self, *args, **kwargs):
        # call original initializator
        super(ContactForm, self).__init__(*args, **kwargs)

        # this helper object allows us to customize form
        self.helper = FormHelper()

        # form tag attributes
        self.helper.form_class = 'form-horizontal'
        self.helper.form_method = 'post'
        self.helper.form_action = reverse('students:contact_admin')

        # twitter bootstrap styles
        self.helper.help_text_inline = True
        self.helper.html5_required = True
        self.helper.label_class = 'col-sm-2 control-label'
        self.helper.field_class = 'col-sm-10'

        # form buttons
        self.helper.add_input(Submit('send_button', u'Надіслати'))

    from_email = forms.EmailField(label=u"Ваша Емейл Адреса")

    subject = forms.CharField(label=u"Заголовок листа", max_length=128)

    message = forms.CharField(label=u"Текст повідомлення", widget=forms.Textarea)

Mysite/students/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.auth.decorators import login_required
from django.core.mail import send_mail


from django.views.generic.base import TemplateView


from students.models import Student, Group, Exam
from students.forms import GroupsForm, ExamForm, StudentForm, ContactForm


# Create your views here.
def index(request):
    return render(request, 'students/index.html')


def student_list(request):
    students = Student.objects.all()

    order_by = request.GET.get('order_by', '')
    if order_by in ('last_name', 'first_name', 'ticket'):
        students = students.order_by(order_by)
        if request.GET.get('reverse', '') == '1':
            students = students.reverse()

    # paginate students
    paginator = Paginator(students, 2)
    page = request.GET.get('page')

    try:
        students = paginator.page(page)

    except PageNotAnInteger:
        students = paginator.page(1)

    except EmptyPage:
        students = paginator.page(paginator.num_pages)

    context = {'students': students}
    return render(request, 'students/student_list.html', context)


def group_list(request):

    groups = Group.objects.all()
    order_by = request.GET.get('order_by', '')
    if order_by in ('title', 'leader'):
        groups = groups.order_by(order_by)
        if request.GET.get('reverse', '') == '1':
            groups = groups.reverse()
    context = {'groups': groups}
    return render(request, 'students/group_list.html', context)


def exam_list(request):

    exams = Exam.objects.all()
    context = {'exams':exams}
    return render(request, 'students/exam_list.html', context)

@login_required
def add_student(request):
    if request.method != 'POST':
        form = StudentForm()

    else:
        form = StudentForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(u'%s?status_message=Студента додано!' %reverse('students:student_list'))

    context = {'form': form}
    return render(request, 'students/add_student.html', context)

@login_required
def add_exam(request):
    if request.method != 'POST':
        form = ExamForm()
    else:
        form = ExamForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(u'%s?status_message=Іспит додано!' %reverse('students:exam_list'))

    context = {'form': form}
    return render(request, 'students/add_exam.html', context)


@login_required
def delete_exam(request, exam_id):
    exam = Exam.objects.get(id=exam_id)
    exam.delete()
    return HttpResponseRedirect(u'%s?status_message=Іспит видалено!' %reverse('students:exam_list'))


@login_required
def delete_student(request, student_id):
    student = Student.objects.get(id=student_id)
    student.delete()
    return HttpResponseRedirect(u'%s?status_message=Студента видалено!' %reverse('students:student_list'))


@login_required
def edit_exam(request, exam_id):
    exam = Exam.objects.get(id=exam_id)

    if request.method != 'POST':
        form = ExamForm(instance=exam)

    else:
        if request.POST.get('cancel_button') is not None:
            return HttpResponseRedirect(u'%s?status_message=Зміни скасовано' %reverse('students:exam_list'))
        elif request.POST.get('save_button') is not None:
            form = ExamForm(instance=exam, data=request.POST)
            if form.is_valid():
                form.save()
                return HttpResponseRedirect(u'%s?status_message=Зміни збережено!' % reverse('students:exam_list'))

    context = {'exam':exam, 'form':form}
    return render(request, 'students/edit_exam.html', context)

@login_required
def edit_student(request, student_id):
    student = Student.objects.get(id=student_id)

    if request.method != 'POST':
        form = StudentForm(instance=student)

    else:
        if request.POST.get('cancel_button') is not None:
            return HttpResponseRedirect(u'%s?status_message=Зміни скасовано' %reverse('students:student_list'))
        elif request.POST.get('save_button') is not None:
            form = StudentForm(instance=student, data=request.POST)
            if form.is_valid():
                form.save()
                return HttpResponseRedirect(u'%s?status_message=Зміни збережено!' %reverse('students:student_list'))

    context = {'student': student, 'form': form}
    return render(request, 'students/edit_student.html', context)

@login_required
def add_group(request):

    if request.method != 'POST':
        form = GroupsForm()
    else:
        form = GroupsForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(u'%s?status_message=Групу додано!' %reverse('students:group_list'))

    context = {'form': form}
    return render(request,'students/add_group.html', context)

@login_required
def edit_group(request, group_id):
    group = Group.objects.get(id=group_id)

    if request.method != 'POST':
        form = GroupsForm(instance=group)
    else:
        if request.POST.get('cancel_button') is not None:
            return HttpResponseRedirect(u'%s?status_message=Зміни скасовано' %reverse('students:group_list'))
        elif request.POST.get('save_button') is not None:
            form = GroupsForm(instance=group, data=request.POST)
            if form.is_valid():
                form.save()
                return HttpResponseRedirect(u'%s?status_message=Зміни збережено!' %reverse('students:group_list'))

    context = {'group': group, 'form': form}
    return render(request, 'students/edit_group.html', context)


def journal(request):

    return render(request, 'students/journal.html')


def contact_admin(request):
    ADMIN_EMAIL = 'admin@studentsdb.com'
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            subject = form.cleaned_data['subject']
            massage = form.cleaned_data['message']
            from_email = form.cleaned_data['from_email']

            try:
                send_mail(subject, massage, from_email, [ADMIN_EMAIL])
            except Exception:
                return HttpResponseRedirect(
                    u'%s?status_message=Під час відправки листа виникла непередбачувана ' \
                    u'помилка. Спробуйте скористатись даною формою пізніше.' % reverse('students:contact_admin'))

            else:
                return HttpResponseRedirect(u'%s?status_message=Повідомлення успішно надіслане!' %reverse('students:contact_admin'))

    else:
        form = ContactForm()
    context = {'form': form}
    return render(request, 'students/contact_admin.html', context)

Mysite/students/templates/students/add_exam.html
{% extends "students/base.html" %}
{% load i18n %}
{% load bootstrap3 %}
{% block header %}
<h2>Add Exam</h2>
{% endblock header %}

{% block content %}

    <form action="{% url 'students:add_exam' %}" method="post" class="form">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
        <button type="submit" name="add_button" class="btn btn-primary">{% trans "Add" %}</button>
        {% endbuttons %}
    </form>

{% endblock content %}

Mysite/students/templates/students/add_group.html
{% extends "students/base.html" %}
{% load i18n %}
{% load bootstrap3 %}

{% block header %}
<h2>Add Group</h2>
{% endblock header %}

{% block content %}

    <form action="{% url 'students:add_group' %}" method="post" class="form">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
        <button type="submit" name="add_button" class="btn btn-primary">{% trans "Add" %}</button>
        {% endbuttons %}
    </form>

{% endblock content %}

Mysite/students/templates/students/add_student.html
{% extends "students/base.html" %}
{% load i18n %}
{% load bootstrap3 %}

{% block header %}
<h2>Add Student</h2>
{% endblock header %}

{% block content %}

    <form action="{% url 'students:add_student' %}" method="post" class="form">
        {% csrf_token %}
       {% bootstrap_form form %}
        {% buttons %}
        <button type="submit" name="add_button" class="btn btn-primary">{% trans "Add" %}</button>
        {% endbuttons %}
    </form>

{% endblock content %}

Mysite/students/templates/students/base.html
{% load i18n %}
{% load static from staticfiles %}

<!DOCTYPE html>
<html lang="uk">
<head>
  <meta charset="UTF-8"/>
  <title>{% trans "Students Accounting Service" %}</title>
  <meta name="description" value="Система Обліку Студентів Навчального Закладу" />
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <link rel="stylesheet"
        href="https://cdn.jsdelivr.net/bootstrap/3.3.0/css/bootstrap.min.css">
  <link rel="stylesheet"
        href="/static/css/main.css">

</head>
<body>

  <!-- Start Container -->
  <div class="container">

    <!-- Start Header -->
    <div class="row" id="header">
      <div class="col-xs-6">
        <h1>{% trans "Students Accounting Service" %}</h1>
      </div>
      {% if user.is_authenticated %}
      <div class="col-xs-4" id="group-selector">
        <strong>{% trans "Group:" %}</strong>
        <select>
          <option value="">Усі Студенти</option>
          <option value="">Мтм-21, Віталій Подоба</option>
          <option value="">Мтм-22, Андрій Петров</option>
        </select>
      </div>
      <div class="col-xs-2" id="user-toolbar">
        <span>{{ user.username }}</span> |
        <a href="{% url 'users:logout' %}">{% trans "Logout" %}</a>
      </div>
      {% else %}
      <div class="col-xs-6" id="user-toolbar">
        <a href="{% url 'users:login' %}">{% trans "Login" %}</a>
        <a href="{% url 'users:register' %}">{% trans "Register" %}</a>
      </div>
      {% endif %}
    </div>
    <!-- End Header -->

    <!-- Start subheader -->
    <div class="row" id="sub-header">
      <div class="col-xs-12">
        <ul class="nav nav-tabs" role="tablist">
          <li role="presentation" {% if request.path == '/' %}class="active"{% endif %}><a href="{% url  'students:student_list' %}">{% trans "Students" %}</a></li>
          <li role="presentation" {% if '/group_list' in request.path %}class="active"{% endif %}><a href="{% url 'students:group_list' %}">{% trans "Groups" %}</a></li>
          <li role="presentation" {% if '/exam_list' in request.path %}class="active"{% endif %}><a href="/exam_list">{% trans "Exams" %}</a></li>
          <li role="presentation" {% if '/contact_admin' in request.path %}class="active"{% endif %}><a href="/contact_admin">{% trans "Contact admin" %}</a></li>

        </ul>
      </div>
    </div>
    <!-- End subheader -->

    <!-- Start Content Columns -->
    <div class="row" id="content-columns">
      <div class="col-xs-12" id="content-column">

        {% block status_message %}
        {% if request.GET.status_message %}
        <div class="alert alert-warning" role="alert">{{ request.GET.status_message }}</div>
        {% endif %}
        {% endblock %}


        {% block header %}{% endblock header %}


        {% block content %}{% endblock content %}


        <!-- End Students Listing -->
      </div>
    </div>
    <!-- End Content Columns -->

    <!-- Start Footer -->
    <div class="row" id="footer">
      <div class="col-xs-12">
        &copy; 2017 {% trans "Students Accounting Service" %}
      </div>
    </div>
    <!-- End Footer -->

  </div>
  <!-- End Container -->

  <!-- Javascripts Inclusion -->
  <script src="http://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
  <script src="https://cdn.jsdelivr.net/bootstrap/3.3.0/js/bootstrap.min.js"></script>
</body>
</html>

Mysite/students/templates/students/base1.html
<p>
	 <a href="{% url 'students:index' %}">Learning Log</a>
	 <a href="{% url 'students:student_list' %}?order_by=last_name">Список студентів </a>
	 <a href="{% url 'students:group_list' %}">Список груп </a>
	<a href="{% url 'students:exam_list' %}">Список іспитів </a>
</p>
{% block content %}{% endblock content %}

Mysite/students/templates/students/edit_exam.html
{% extends "students/base.html" %}
{% load i18n %}
{% load bootstrap3 %}


{% block header %}
<h2>Edit Exam</h2>
{% endblock header %}


{% block content %}

    <form action="{% url 'students:edit_exam' exam.id%}" method="post" class="form">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
        <button type="submit" name="save_button" class="btn btn-primary">{% trans "Save" %}</button> <button type="submit" name="cancel_button" class="btn btn-primary">{% trans "Cancel" %}</button>
        {% endbuttons %}
    </form>

{% endblock content %}

Mysite/students/templates/students/edit_student.html
{% extends "students/base.html" %}
{% load i18n %}
{% load bootstrap3 %}


{% block header %}
<h2>Edit Student</h2>
{% endblock header %}

{% block content %}

    <form action="{% url 'students:edit_student' student.id%}" method="post" class="form">
        {% csrf_token %}
         {% bootstrap_form form %}
        {% buttons %}
        <button type="submit" name="save_button" class="btn btn-primary">{% trans "Save" %}</button> <button type="submit" name="cancel_button" class="btn btn-primary">{% trans "Cancel" %}</button>
        {% endbuttons %}
    </form>

{% endblock content %}

Mysite/students/templates/students/exam_list.html
{% extends 'students/base.html' %}
{% load i18n %}

{% load static from staticfiles %}

{% block content %}

<a href="{% url 'students:add_exam' %}" class="btn btn-primary">{% trans "Add Exam" %}</a>

<table class="table">
	 <thead>
		<tr>
			<td>#</td>
			<td>{% trans "Subject" %}</td>
			<td>{% trans "Data" %}</td>
            <td>{% trans "Teacher" %}</td>
		</tr>
	 </thead>
	<tbody>
	{% for exam in exams %}
	<tr>
		<td>{{ forloop.counter }}</td>
		<td><a href="{% url 'students:edit_exam' exam.id %}">{{ exam.title }}</td>
		<td>{{ exam.data }}</td>
        <td>{{ exam.ticher_name }}</td>
        <td>{{ exam.exam_group }}</td>
		<td>
        <div class="btn-group">
          <button type="button" class="btn btn-default dropdown-toggle"
                  data-toggle="dropdown">Дія
            <span class="caret"></span>
          </button>
			<ul class="dropdown-menu" role="menu">
           	 	<li><a href="{% url 'students:edit_exam' exam.id %}">Редагувати</a></li>
				<li><a href="{% url 'students:edit_exam' exam.id %}">Відвідування</a></li>
            	<li><a href="{% url 'students:delete_exam' exam.id %}">Видалити</a></li>
          	</ul>

        </div>
      </td>
	</tr>
	{% endfor %}
	</tbody>
</table>


{% endblock content %}

Mysite/students/templates/students/group_list.html
{% extends 'students/base.html' %}
{% load i18n %}

{% load static from staticfiles %}

{% block content %}

<a href="{% url 'students:add_group' %}" class="btn btn-primary">{% trans "Add Groups" %} </a>

<table class="table">
	{% with order_by=request.GET.order_by reverse=request.GET.reverse %}
	 <thead>
		<tr>
			<td>#</td>
			<td>
				<a href="{% url 'students:group_list' %}?order_by=title{% if order_by == 'title' and reverse != '1' %}&amp;reverse=1{% endif %}">
          		№
          		{% if order_by == 'title' and reverse != '1' %}&uarr;
          		{% elif order_by == 'title' and reverse == '1' %}&darr;
					{% endif %}</a>
			</td>

			<td>
				<a href="{% url 'students:group_list' %}?order_by=leader{% if order_by == 'leader' and reverse != '1' %}&amp;reverse=1{% endif %}">
          		{% trans "Leader" %}
          		{% if order_by == 'leader' and reverse != '1' %}&uarr;
          		{% elif order_by == 'leader' and reverse == '1' %}&darr;
					{% endif %}</a>
			</td>
		</tr>

	 </thead>
	{% endwith %}
	<tbody>
	{% for group in groups %}
	<tr>
		<td>{{ forloop.counter }}</td>
		<td><a href="{% url 'students:edit_group' group.id %}">{{ group.title }}</a></td>
		<td>{{ group.leader }}</td>
		<td>
        <div class="btn-group">
          <button type="button" class="btn btn-default dropdown-toggle"
                  data-toggle="dropdown">Дія
            <span class="caret"></span>
          </button>
			<ul class="dropdown-menu" role="menu">
           	 	<li><a href="{% url 'students:edit_group' group.id %}">Редагувати</a></li>
				<li><a href="{% url 'students:edit_group' group.id %}">Відвідування</a></li>
            	<li><a href="{% url 'students:edit_group' group.id %}">Видалити</a></li>
          	</ul>

        </div>
      </td>
	</tr>
	{% endfor %}
	</tbody>
</table>


{% endblock content %}

Mysite/students/templates/students/student_list.html
{% extends 'students/base.html' %}
{% load i18n %}

{% load static from staticfiles %}


{% block content  %}

<a href="{% url 'students:add_student' %}" class="btn btn-primary">{% trans "Add Student" %}</a>

<!-- Start Students Listing -->
<table class="table">
  {% with order_by=request.GET.order_by reverse=request.GET.reverse %}
  <thead>
    <tr>
      <th>#</th>
      <th> {% trans "Photo" %}</th>
      <th>
        <a href="{% url 'students:student_list' %}?order_by=last_name{% if order_by == 'last_name' and reverse != '1' %}&amp;reverse=1{% endif %}">
          {% trans "Last Name" %}
          {% if order_by == 'last_name' and reverse != '1' %}&uarr;
          {% elif order_by == 'last_name' and reverse == '1' %}&darr;
          {% endif %}
        </a>
      </th>
      <th>
        <a href="{% url 'students:student_list' %}?order_by=first_name{% if order_by == 'first_name' and reverse != '1' %}&amp;reverse=1{% endif %}">
          {% trans "First Name" %}
          {% if order_by == 'first_name' and reverse != '1' %}&uarr;
          {% elif order_by == 'first_name' and reverse == '1' %}&darr;
          {% endif %}</a>
      </th>
      <th>
        <a href="{% url 'students:student_list' %}?order_by=ticket{% if order_by == 'ticket' and reverse != '1' %}&amp;reverse=1{% endif %}">
          {% trans "Ticket #" %}
          {% if order_by == 'ticket' and reverse != '1' %}&uarr;
          {% elif order_by == 'ticket' and reverse == '1' %}&darr;
          {% endif %}</a>
      </th>
      <th>{% trans "Actions" %}</th>
    </tr>
  </thead>
  {% endwith %}
  <tbody>
    {% for student in students %}
    <tr>
      <td>{{ forloop.counter }}</td>
		<td>
        {% if student.photo %}
          <img class="img-circle" src="{{ student.photo.url }}" height="30"
               width="30" />
        {% else %}
          <img class="img-circle" src="{% static 'img/default_user.png' %}"
               height="30" width="30" />
        {% endif %}
      </td>
      <td><a href="{% url 'students:edit_student' student.id %}">{{ student.last_name }}</a></td>
      <td><a href="{% url 'students:edit_student' student.id %}">{{ student.first_name }}</a></td>
      <td>{{ student.ticket }}</td>
      <td>
        <div class="btn-group">
          <button type="button" class="btn btn-default dropdown-toggle"
                  data-toggle="dropdown">Дія
            <span class="caret"></span>
          </button>
			<ul class="dropdown-menu" role="menu">
           	 	<li><a href="{% url 'students:edit_student' student.id %}">Редагувати</a></li>
				<li><a href="{% url 'students:edit_student' student.id %}">Відвідування</a></li>
            	<li><a href="{% url 'students:delete_student' student.id %}">Видалити</a></li>
          	</ul>

        </div>
      </td>
    </tr>
    {% endfor %}

  </tbody>
</table>
<!-- End Students Listing -->


<!-- Paginator -->

{% if students.has_other_pages %}
{% with order_by=request.GET.order_by reverse=request.GET.reverse %}
<nav>
  <ul class="pagination">
    <li><a href="{% url 'students:student_list' %}?page=1
                  &amp;order_by={{order_by}}&amp;reverse={{reverse}}">&laquo;</a> </li>
    {% for p in students.paginator.page_range %}
    <li {% if students.number == p %}class="active"{% endif %}>
      <a href="{% url 'students:student_list' %}?page={{p}}
                &amp;order_by={{order_by}}&amp;reverse={{reverse}}">{{p}}</a>
    </li>
    {% endfor %}
    <li>
      <a href="{% url 'students:student_list' %}?page={{students.paginator.num_pages}}
                &amp;order_by={{order_by}}&amp;reverse={{reverse}}">&raquo;</a>

    </li>
  </ul>
</nav>
{% endwith %}
{% endif %}


{% endblock content  %}